---
abstract: 'Module and CLI for creating engineered sequences'
author:
  - 'Ray Miller, Sajith Perera'
build_requires:
  Class::Data::Inheritable: 0
  File::Temp: 0
  FindBin: 0
  IO::String: 0
  Test::Class: 0
  Test::Most: 0
  YAML: 0
  base: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300014, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Eng-Seq-Builder
requires:
  Bio::Annotation::Collection: 0
  Bio::Annotation::Comment: 0
  Bio::EnsEMBL::Registry: 0
  Bio::Range: 0
  Bio::Seq: 0
  Bio::SeqFeature::Gene::Exon: 0
  Bio::SeqFeature::Generic: 0
  Bio::SeqFeatureI: 0
  Bio::SeqIO: 0
  Bio::SeqUtils: 0
  Bio::Species: 0
  Carp: 0
  Const::Fast: 0
  DBIx::Class::Core: 0
  DBIx::Class::Schema: 0
  Data::Dump: 0
  Hash::MoreUtils: 0
  List::MoreUtils: 0
  List::Util: 0
  Log::Log4perl: 0
  Moose: 0
  Moose::Role: 0
  MooseX::App::Cmd: 0
  MooseX::App::Cmd::Command: 0
  MooseX::ClassAttribute: 0
  MooseX::Log::Log4perl: 0
  MooseX::NonMoose: 0
  MooseX::Params::Validate: 0
  MooseX::SimpleConfig: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Path::Class: 0
  Sub::Exporter: 0
  Text::Table: 0
  Throwable::Error: 0
  Try::Tiny: 0
  YAML::Any: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
version: 0.002
